apiVersion: apps/v1
kind: Deployment
metadata:
  name: grandnode2
  namespace: grandnode2
  labels:
    app: grandnode2
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: {{ .Values.deploymentStrategy.maxUnavailable }}
      maxSurge: {{ .Values.deploymentStrategy.maxSurge }}
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      app: grandnode2
  template:
    metadata:
      labels:
        app: grandnode2
    spec:
      containers:
        - name: grandnode2
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.container.port }}
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "{{ .Values.env.ASPNETCORE_ENVIRONMENT }}"
            - name: DB_CONNECTION_STRING
              value: "{{ .Values.env.DB_CONNECTION_STRING }}"
            - name: ConnectionStrings__Mongodb
              value: "{{ .Values.env.CONNECTIONSTRINGS_MONGODB }}"
            - name: ConnectionStrings__Provider
              value: "{{ .Values.env.CONNECTIONSTRINGS_PROVIDER }}"
            - name: FeatureManagement__Grand.Module.Installer
              value: "{{ .Values.env.FEATURE_INSTALLER }}"
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu | quote }}
              memory: {{ .Values.resources.requests.memory | quote }}
            limits:
              cpu: {{ .Values.resources.limits.cpu | quote }}
              memory: {{ .Values.resources.limits.memory | quote }}
          {{- if .Values.probes.readiness.enabled }}
          readinessProbe:
            {{- if eq .Values.probes.readiness.type "http" }}
            httpGet:
              path: {{ .Values.probes.readiness.path | quote }}
              port: {{ .Values.probes.readiness.port }}
            {{- else }}
            tcpSocket:
              port: {{ .Values.probes.readiness.port }}
            {{- end }}
            initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.readiness.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.readiness.timeoutSeconds }}
            failureThreshold: {{ .Values.probes.readiness.failureThreshold }}
          {{- end }}
          {{- if .Values.probes.liveness.enabled }}
          livenessProbe:
            {{- if eq .Values.probes.liveness.type "http" }}
            httpGet:
              path: {{ .Values.probes.liveness.path | quote }}
              port: {{ .Values.probes.liveness.port }}
            {{- else }}
            tcpSocket:
              port: {{ .Values.probes.liveness.port }}
            {{- end }}
            initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.liveness.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.liveness.timeoutSeconds }}
            failureThreshold: {{ .Values.probes.liveness.failureThreshold }}
          {{- end }}
